version: '3.8'   # Compose file format version

# This Compose stack runs Jenkins and a Docker-in-Docker (DinD) service.
# Both share the same named volume (jenkins-data) so Jenkins jobs and DinD
# see the same /var/jenkins_home workspace.

services:
  docker:
    image: docker:dind
    container_name: docker
    privileged: true                # Required for DinD to run Docker daemon
    environment:
      - DOCKER_TLS_CERTDIR=/certs    # Enable TLS certs for secure Docker API
    ports:
      - "2376:2376"                  # Expose Docker daemon port
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - jenkins-data:/var/jenkins_home   # Shared volume with Jenkins
    networks:
      - jenkins

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    user: root                       # Run as root to access Docker CLI
    restart: unless-stopped
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    ports:
      - "8080:8080"                  # Jenkins UI
      - "50000:50000"                # Agent communication
    volumes:
      - docker-certs-client:/certs/client:ro
      - jenkins-data:/var/jenkins_home
      - ./jenkins_init/01-security.groovy:/var/jenkins_home/init.groovy.d/01-security.groovy:ro
      - /usr/bin/docker:/usr/bin/docker   # Map host docker CLI inside Jenkins
    networks:
      - jenkins
    depends_on:
      - docker

volumes:
  jenkins-data:        # Shared Jenkins home
  docker-certs-ca:     # CA certs for TLS
  docker-certs-client: # Client certs for Jenkins

networks:
  jenkins:
    driver: bridge
